name: Publish to WinGet

on:
  workflow_dispatch:  # This makes the workflow manually triggerable from the GitHub UI

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Publish to WinGet (.exe)
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: NomanDhoni.BlinkEye  # Replace with your app identifier
          installers-regex: '\.exe$'  # Only .exe files
          token: ${{ secrets.WINGET_TOKEN_BLINK_EYE }}
          
      - name: Publish to WinGet (.msi)
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: NomanDhoni.BlinkEye  # Replace with your app identifier
          installers-regex: '\.msi$'  # Only .msi files
          token: ${{ secrets.WINGET_TOKEN_BLINK_EYE }}
