name: Publish to WinGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release to publish'
        required: true
        default: 'v2.5.0'  # Optional: You can set a default version 

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: NomanDhoni.BlinkEye
          release-tag: ${{ github.event.inputs.version }}  # Access version input
          max-versions-to-keep: 5 # keep only latest 5 versions
          token: ${{ secrets.WINGET_TOKEN_BLINK_EYE }}
